# Site setings
name: 'Faizan Muhammad'
description: 'SWE @ Google (EngRes)'
meta_description: 'Personal Site'
logo:
# Author image is used in site sidebar and greetings in the home page hero text
author:
  image: 'portrait.png'
  greetings: ""
favicon: 'assets/images/favicon.ico'
baseurl: 
production_url: https://faizan-m.github.io/
disqus: 
mailchimp_url: 
# Add your GA Tracking Id
ga_analytics: "UA-152060403-1"

# Contact form setings
email: youremail@email.com
contact_page_description: "."
thankyou_page_description: "."

# Social links
twitter: 
facebook: 
github: 'faizan-m'
codepen: 
dribbble: 
medium:
instagram: 
pinterest:
linkedin: 'faizan-muham'
producthunt:
quora:
scholar: 'citations?hl=en&user=ZmnQkLMAAAAJ'

# Navigation
navigation:
  - text: Home
    url: /
  - text: Education
    url: /education
  - text: Work Experience
    url: /work
  - text: Research Experience
    url: /research
  - text: Projects
    url: /projects
  - text: Publications
    url: /publications
  - text: Activities
    url: /activities
  - text: Resume
    url: /resume
  - text: Search
    url: /search

# Pagination
paginate: 5
paginate_path: /page:num/

# Permalinks
permalink: /:title

# Other
markdown: kramdown

# Sass
sass:
  sass_dir: _sass
  style: compressed

gems:
  - jekyll-paginate
  - jekyll-tagsgenerator
  - jekyll-seo-tag
  - jekyll-sitemap

plugins_dir:
  - jekyll-paginate
  - jekyll-tagsgenerator
  - jekyll-seo-tag
  - jekyll-sitemap

plugins:
  - jekyll-paginate
  - jekyll-tagsgenerator
  - jekyll-seo-tag
  - jekyll-sitemap