# Site setings
name: 'Faizan Muhammad'
description: '(Almost) Software Engineer'
meta_description: 'Personal Site'
logo:
# Author image is used in site sidebar and greetings in the home page hero text
author:
  image: 'portrait.png'
  greetings: "My name is Faizan Muhammad. I'm an undergraduate student studying Computer Science at Tufts University. It’s nice to meet you."
favicon: 'assets/images/favicon.ico'
baseurl: 
production_url: https://faizan-m.github.io/
disqus: 
mailchimp_url: 
# Add your GA Tracking Id
ga_analytics: "UA-152060403-1"

# Contact form setings
email: youremail@email.com
contact_page_description: "."
thankyou_page_description: "."

# Social links
twitter: 
facebook: 
github: 'faizan-m'
codepen: 
dribbble: 
medium: 
instagram: 
pinterest:
linkedin: 'faizan-muham'
producthunt:
quora:

# Navigation
navigation:
  - text: Home
    url: /
  - text: Experience
    url: /experience
  - text: Projects
    url: /projects
  - text: Activities
    url: /activities
  - text: Resume
    url: /assets/docs/Faizan_Resume.pdf
  - text: Search
    url: /search

# Required Plugins
plugins_dir:
  - jekyll-paginate
  - jekyll-tagsgenerator
  - jekyll-seo-tag
  - jekyll-sitemap

# Pagination
paginate: 5
paginate_path: /page:num/

# Permalinks
permalink: /:title

# Other
markdown: kramdown

# Sass
sass:
  sass_dir: _sass
  style: compressed
